/**
 * Isveski Client Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BeaconParameter {
    'beaconId'?: string | null;
    'parameter'?: string | null;
    'ticketId'?: string;
    'discovered'?: boolean;
    'eventTime'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "beaconId",
            "baseName": "beaconId",
            "type": "string"
        },
        {
            "name": "parameter",
            "baseName": "parameter",
            "type": "string"
        },
        {
            "name": "ticketId",
            "baseName": "ticketId",
            "type": "string"
        },
        {
            "name": "discovered",
            "baseName": "discovered",
            "type": "boolean"
        },
        {
            "name": "eventTime",
            "baseName": "eventTime",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return BeaconParameter.attributeTypeMap;
    }
}

