"use strict";
/**
 * Isveski Client Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BeaconResult = void 0;
class BeaconResult {
    static getAttributeTypeMap() {
        return BeaconResult.attributeTypeMap;
    }
}
exports.BeaconResult = BeaconResult;
BeaconResult.discriminator = undefined;
BeaconResult.attributeTypeMap = [
    {
        "name": "_continue",
        "baseName": "continue",
        "type": "boolean"
    }
];
//# sourceMappingURL=beaconResult.js.map