"use strict";
/**
 * Isveski Client Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestTicket = void 0;
class RequestTicket {
    static getAttributeTypeMap() {
        return RequestTicket.attributeTypeMap;
    }
}
exports.RequestTicket = RequestTicket;
RequestTicket.discriminator = undefined;
RequestTicket.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "ticketDefinitionId",
        "baseName": "ticketDefinitionId",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "string"
    }
];
//# sourceMappingURL=requestTicket.js.map