"use strict";
/**
 * Isveski Client Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestParameter = void 0;
class RequestParameter {
    static getAttributeTypeMap() {
        return RequestParameter.attributeTypeMap;
    }
}
exports.RequestParameter = RequestParameter;
RequestParameter.discriminator = undefined;
RequestParameter.attributeTypeMap = [
    {
        "name": "sensorId",
        "baseName": "sensorId",
        "type": "string"
    },
    {
        "name": "sensorName",
        "baseName": "sensorName",
        "type": "string"
    },
    {
        "name": "clientName",
        "baseName": "clientName",
        "type": "string"
    },
    {
        "name": "userId",
        "baseName": "userId",
        "type": "string"
    },
    {
        "name": "communicationId",
        "baseName": "communicationId",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "language",
        "baseName": "language",
        "type": "string"
    },
    {
        "name": "tickets",
        "baseName": "tickets",
        "type": "Array<RequestTicket>"
    }
];
//# sourceMappingURL=requestParameter.js.map