/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ActionTypesEnum {
    Nothing = <any> 'Nothing',
    ShowTicket = <any> 'ShowTicket',
    RefreshTicket = <any> 'RefreshTicket',
    RefreshTicketList = <any> 'RefreshTicketList',
    Sensor = <any> 'Sensor',
    ShowUrl = <any> 'ShowUrl',
    ShowMenu = <any> 'ShowMenu',
    ShowMessage = <any> 'ShowMessage',
    ShowMultiple = <any> 'ShowMultiple',
    ShowPrompt = <any> 'ShowPrompt',
    ShowQrCode = <any> 'ShowQrCode',
    BioAuthenticate = <any> 'BioAuthenticate',
    ListenToBeacons = <any> 'ListenToBeacons',
    NoTicket = <any> 'NoTicket',
    ShowWebPage = <any> 'ShowWebPage'
}
