"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActionType = void 0;
var ActionType;
(function (ActionType) {
    ActionType[ActionType["NUMBER_1"] = 1] = "NUMBER_1";
    ActionType[ActionType["NUMBER_2"] = 2] = "NUMBER_2";
    ActionType[ActionType["NUMBER_3"] = 3] = "NUMBER_3";
})(ActionType = exports.ActionType || (exports.ActionType = {}));
//# sourceMappingURL=actionType.js.map