"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BioMetricAuthenticationResult = void 0;
class BioMetricAuthenticationResult {
    static getAttributeTypeMap() {
        return BioMetricAuthenticationResult.attributeTypeMap;
    }
}
exports.BioMetricAuthenticationResult = BioMetricAuthenticationResult;
BioMetricAuthenticationResult.discriminator = undefined;
BioMetricAuthenticationResult.attributeTypeMap = [
    {
        "name": "succeeded",
        "baseName": "succeeded",
        "type": "boolean"
    },
    {
        "name": "authenticationMethod",
        "baseName": "authenticationMethod",
        "type": "AuthenticationMethod"
    }
];
//# sourceMappingURL=bioMetricAuthenticationResult.js.map