"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Choice = void 0;
class Choice {
    static getAttributeTypeMap() {
        return Choice.attributeTypeMap;
    }
}
exports.Choice = Choice;
Choice.discriminator = undefined;
Choice.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "number"
    },
    {
        "name": "text",
        "baseName": "text",
        "type": "string"
    },
    {
        "name": "defaultValue",
        "baseName": "defaultValue",
        "type": "boolean"
    }
];
//# sourceMappingURL=choice.js.map