"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientWallet = void 0;
class ClientWallet {
    static getAttributeTypeMap() {
        return ClientWallet.attributeTypeMap;
    }
}
exports.ClientWallet = ClientWallet;
ClientWallet.discriminator = undefined;
ClientWallet.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "userName",
        "baseName": "userName",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "phoneNumber",
        "baseName": "phoneNumber",
        "type": "string"
    },
    {
        "name": "tickets",
        "baseName": "tickets",
        "type": "Array<ClientWalletTicket>"
    }
];
//# sourceMappingURL=clientWallet.js.map