"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientWalletTicket = void 0;
class ClientWalletTicket {
    static getAttributeTypeMap() {
        return ClientWalletTicket.attributeTypeMap;
    }
}
exports.ClientWalletTicket = ClientWalletTicket;
ClientWalletTicket.discriminator = undefined;
ClientWalletTicket.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "ticketDefinitionId",
        "baseName": "ticketDefinitionId",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "string"
    },
    {
        "name": "template",
        "baseName": "template",
        "type": "Template"
    },
    {
        "name": "detailTemplate",
        "baseName": "detailTemplate",
        "type": "DetailTemplate"
    },
    {
        "name": "pushNotifications",
        "baseName": "pushNotifications",
        "type": "TicketAccess"
    },
    {
        "name": "beacons",
        "baseName": "beacons",
        "type": "TicketAccess"
    },
    {
        "name": "locations",
        "baseName": "locations",
        "type": "TicketAccess"
    }
];
//# sourceMappingURL=clientWalletTicket.js.map