"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClientTicketAction = void 0;
class ClientTicketAction {
    static getAttributeTypeMap() {
        return ClientTicketAction.attributeTypeMap;
    }
}
exports.ClientTicketAction = ClientTicketAction;
ClientTicketAction.discriminator = undefined;
ClientTicketAction.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "actionType",
        "baseName": "actionType",
        "type": "ActionType"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "data",
        "baseName": "data",
        "type": "string"
    },
    {
        "name": "presentationData",
        "baseName": "presentationData",
        "type": "string"
    },
    {
        "name": "presentationType",
        "baseName": "presentationType",
        "type": "string"
    },
    {
        "name": "actionTime",
        "baseName": "actionTime",
        "type": "Date"
    },
    {
        "name": "note",
        "baseName": "note",
        "type": "string"
    }
];
//# sourceMappingURL=clientTicketAction.js.map