/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DetailTemplate } from './detailTemplate';
import { Template } from './template';

export class CreateTicketDto {
    'userId'?: string;
    'name'?: string | null;
    'ticketDefinitionId'?: string;
    'data'?: string | null;
    'detailTemplate'?: DetailTemplate;
    'template'?: Template;
    'note'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ticketDefinitionId",
            "baseName": "ticketDefinitionId",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string"
        },
        {
            "name": "detailTemplate",
            "baseName": "detailTemplate",
            "type": "DetailTemplate"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Template"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateTicketDto.attributeTypeMap;
    }
}

