"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DetailTemplateTypeEnum = void 0;
var DetailTemplateTypeEnum;
(function (DetailTemplateTypeEnum) {
    DetailTemplateTypeEnum[DetailTemplateTypeEnum["Dt1"] = 'DT1'] = "Dt1";
})(DetailTemplateTypeEnum = exports.DetailTemplateTypeEnum || (exports.DetailTemplateTypeEnum = {}));
//# sourceMappingURL=detailTemplateTypeEnum.js.map