"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DetailTemplate1 = void 0;
const detailTemplate_1 = require("./detailTemplate");
class DetailTemplate1 extends detailTemplate_1.DetailTemplate {
    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(DetailTemplate1.attributeTypeMap);
    }
}
exports.DetailTemplate1 = DetailTemplate1;
DetailTemplate1.discriminator = undefined;
DetailTemplate1.attributeTypeMap = [
    {
        "name": "image",
        "baseName": "image",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "time",
        "baseName": "time",
        "type": "Date"
    },
    {
        "name": "expiry",
        "baseName": "expiry",
        "type": "Date"
    },
    {
        "name": "buttons",
        "baseName": "buttons",
        "type": "Array<TemplateButton>"
    }
];
//# sourceMappingURL=detailTemplate1.js.map