"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DetailTemplate = void 0;
class DetailTemplate {
    static getAttributeTypeMap() {
        return DetailTemplate.attributeTypeMap;
    }
}
exports.DetailTemplate = DetailTemplate;
DetailTemplate.discriminator = "detailType";
DetailTemplate.attributeTypeMap = [
    {
        "name": "detailType",
        "baseName": "detailType",
        "type": "DetailTemplateTypeEnum"
    }
];
//# sourceMappingURL=detailTemplate.js.map