"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorModel = void 0;
class ErrorModel {
    static getAttributeTypeMap() {
        return ErrorModel.attributeTypeMap;
    }
}
exports.ErrorModel = ErrorModel;
ErrorModel.discriminator = undefined;
ErrorModel.attributeTypeMap = [
    {
        "name": "errorCode",
        "baseName": "errorCode",
        "type": "IceCodeErrors"
    },
    {
        "name": "error",
        "baseName": "error",
        "type": "string"
    }
];
//# sourceMappingURL=errorModel.js.map