"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IceCodeErrors = void 0;
var IceCodeErrors;
(function (IceCodeErrors) {
    IceCodeErrors[IceCodeErrors["NUMBER_1"] = 1] = "NUMBER_1";
    IceCodeErrors[IceCodeErrors["NUMBER_100"] = 100] = "NUMBER_100";
})(IceCodeErrors = exports.IceCodeErrors || (exports.IceCodeErrors = {}));
//# sourceMappingURL=iceCodeErrors.js.map