"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListenToBeaconsDto = void 0;
class ListenToBeaconsDto {
    static getAttributeTypeMap() {
        return ListenToBeaconsDto.attributeTypeMap;
    }
}
exports.ListenToBeaconsDto = ListenToBeaconsDto;
ListenToBeaconsDto.discriminator = undefined;
ListenToBeaconsDto.attributeTypeMap = [
    {
        "name": "communicationId",
        "baseName": "communicationId",
        "type": "string"
    },
    {
        "name": "ticketId",
        "baseName": "ticketId",
        "type": "string"
    },
    {
        "name": "beacons",
        "baseName": "beacons",
        "type": "Array<string>"
    },
    {
        "name": "parameter",
        "baseName": "parameter",
        "type": "string"
    },
    {
        "name": "notifyNotFoundSek",
        "baseName": "notifyNotFoundSek",
        "type": "number"
    },
    {
        "name": "timeoutSek",
        "baseName": "timeoutSek",
        "type": "number"
    }
];
//# sourceMappingURL=listenToBeaconsDto.js.map