"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListenToBeaconsResultDto = void 0;
class ListenToBeaconsResultDto {
    static getAttributeTypeMap() {
        return ListenToBeaconsResultDto.attributeTypeMap;
    }
}
exports.ListenToBeaconsResultDto = ListenToBeaconsResultDto;
ListenToBeaconsResultDto.discriminator = undefined;
ListenToBeaconsResultDto.attributeTypeMap = [
    {
        "name": "succeeded",
        "baseName": "succeeded",
        "type": "boolean"
    }
];
//# sourceMappingURL=listenToBeaconsResultDto.js.map