/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ListenToBeaconsDto {
    'communicationId': string;
    'ticketId': string;
    'beacons': Array<string>;
    'parameter': string;
    'notifyNotFoundSek': number;
    'timeoutSek': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "communicationId",
            "baseName": "communicationId",
            "type": "string"
        },
        {
            "name": "ticketId",
            "baseName": "ticketId",
            "type": "string"
        },
        {
            "name": "beacons",
            "baseName": "beacons",
            "type": "Array<string>"
        },
        {
            "name": "parameter",
            "baseName": "parameter",
            "type": "string"
        },
        {
            "name": "notifyNotFoundSek",
            "baseName": "notifyNotFoundSek",
            "type": "number"
        },
        {
            "name": "timeoutSek",
            "baseName": "timeoutSek",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListenToBeaconsDto.attributeTypeMap;
    }
}

