"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogTemplate = void 0;
class LogTemplate {
    static getAttributeTypeMap() {
        return LogTemplate.attributeTypeMap;
    }
}
exports.LogTemplate = LogTemplate;
LogTemplate.discriminator = "templateType";
LogTemplate.attributeTypeMap = [
    {
        "name": "templateType",
        "baseName": "templateType",
        "type": "LogTemplateTypeEnum"
    }
];
//# sourceMappingURL=logTemplate.js.map