"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogTemplateTypeEnum = void 0;
var LogTemplateTypeEnum;
(function (LogTemplateTypeEnum) {
    LogTemplateTypeEnum[LogTemplateTypeEnum["T1"] = 'T1'] = "T1";
})(LogTemplateTypeEnum = exports.LogTemplateTypeEnum || (exports.LogTemplateTypeEnum = {}));
//# sourceMappingURL=logTemplateTypeEnum.js.map