"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogTemplate1 = void 0;
const logTemplate_1 = require("./logTemplate");
class LogTemplate1 extends logTemplate_1.LogTemplate {
    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(LogTemplate1.attributeTypeMap);
    }
}
exports.LogTemplate1 = LogTemplate1;
LogTemplate1.discriminator = undefined;
LogTemplate1.attributeTypeMap = [
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "time",
        "baseName": "time",
        "type": "Date"
    }
];
//# sourceMappingURL=logTemplate1.js.map