/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PushSensorDto {
    'name'?: string | null;
    'description'?: string | null;
    'ticketIds'?: Array<string> | null;
    'lifeTimeInSeconds'?: number;
    'deviceUserEmail'?: string | null;
    'message'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "ticketIds",
            "baseName": "ticketIds",
            "type": "Array<string>"
        },
        {
            "name": "lifeTimeInSeconds",
            "baseName": "lifeTimeInSeconds",
            "type": "number"
        },
        {
            "name": "deviceUserEmail",
            "baseName": "deviceUserEmail",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PushSensorDto.attributeTypeMap;
    }
}

