"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RefreshTicketAction = void 0;
const baseAction_1 = require("./baseAction");
class RefreshTicketAction extends baseAction_1.BaseAction {
    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(RefreshTicketAction.attributeTypeMap);
    }
}
exports.RefreshTicketAction = RefreshTicketAction;
RefreshTicketAction.discriminator = undefined;
RefreshTicketAction.attributeTypeMap = [
    {
        "name": "ticketId",
        "baseName": "ticketId",
        "type": "string"
    }
];
//# sourceMappingURL=refreshTicketAction.js.map