"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReturnChoice = void 0;
class ReturnChoice {
    static getAttributeTypeMap() {
        return ReturnChoice.attributeTypeMap;
    }
}
exports.ReturnChoice = ReturnChoice;
ReturnChoice.discriminator = undefined;
ReturnChoice.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "number"
    },
    {
        "name": "value",
        "baseName": "value",
        "type": "boolean"
    }
];
//# sourceMappingURL=returnChoice.js.map