"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SensorAction = void 0;
const baseAction_1 = require("./baseAction");
class SensorAction extends baseAction_1.BaseAction {
    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(SensorAction.attributeTypeMap);
    }
}
exports.SensorAction = SensorAction;
SensorAction.discriminator = undefined;
SensorAction.attributeTypeMap = [
    {
        "name": "sensorId",
        "baseName": "sensorId",
        "type": "string"
    }
];
//# sourceMappingURL=sensorAction.js.map