"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Sensor = void 0;
class Sensor {
    static getAttributeTypeMap() {
        return Sensor.attributeTypeMap;
    }
}
exports.Sensor = Sensor;
Sensor.discriminator = undefined;
Sensor.attributeTypeMap = [
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "sensorType",
        "baseName": "sensorType",
        "type": "SensorType"
    },
    {
        "name": "description",
        "baseName": "description",
        "type": "string"
    },
    {
        "name": "enabled",
        "baseName": "enabled",
        "type": "boolean"
    },
    {
        "name": "ticketsActive",
        "baseName": "ticketsActive",
        "type": "Array<TicketActive>"
    }
];
//# sourceMappingURL=sensor.js.map