"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SensorType = void 0;
var SensorType;
(function (SensorType) {
    SensorType[SensorType["Normal"] = 'Normal'] = "Normal";
    SensorType[SensorType["Push"] = 'Push'] = "Push";
    SensorType[SensorType["Beacon"] = 'Beacon'] = "Beacon";
})(SensorType = exports.SensorType || (exports.SensorType = {}));
//# sourceMappingURL=sensorType.js.map