"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowMultipleChoiceResult = void 0;
class ShowMultipleChoiceResult {
    static getAttributeTypeMap() {
        return ShowMultipleChoiceResult.attributeTypeMap;
    }
}
exports.ShowMultipleChoiceResult = ShowMultipleChoiceResult;
ShowMultipleChoiceResult.discriminator = undefined;
ShowMultipleChoiceResult.attributeTypeMap = [
    {
        "name": "statusDetail",
        "baseName": "statusDetail",
        "type": "StatusDetail"
    },
    {
        "name": "choices",
        "baseName": "choices",
        "type": "Array<ReturnChoice>"
    }
];
//# sourceMappingURL=showMultipleChoiceResult.js.map