"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowUrlAction = void 0;
const baseAction_1 = require("./baseAction");
class ShowUrlAction extends baseAction_1.BaseAction {
    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ShowUrlAction.attributeTypeMap);
    }
}
exports.ShowUrlAction = ShowUrlAction;
ShowUrlAction.discriminator = undefined;
ShowUrlAction.attributeTypeMap = [
    {
        "name": "url",
        "baseName": "url",
        "type": "string"
    }
];
//# sourceMappingURL=showUrlAction.js.map