"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowPromptDto = void 0;
class ShowPromptDto {
    static getAttributeTypeMap() {
        return ShowPromptDto.attributeTypeMap;
    }
}
exports.ShowPromptDto = ShowPromptDto;
ShowPromptDto.discriminator = undefined;
ShowPromptDto.attributeTypeMap = [
    {
        "name": "communicationId",
        "baseName": "communicationId",
        "type": "string"
    },
    {
        "name": "image",
        "baseName": "image",
        "type": "string"
    },
    {
        "name": "title",
        "baseName": "title",
        "type": "string"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "yes",
        "baseName": "yes",
        "type": "string"
    },
    {
        "name": "no",
        "baseName": "no",
        "type": "string"
    },
    {
        "name": "timeoutSek",
        "baseName": "timeoutSek",
        "type": "number"
    }
];
//# sourceMappingURL=showPromptDto.js.map