"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShowPromptResult = void 0;
class ShowPromptResult {
    static getAttributeTypeMap() {
        return ShowPromptResult.attributeTypeMap;
    }
}
exports.ShowPromptResult = ShowPromptResult;
ShowPromptResult.discriminator = undefined;
ShowPromptResult.attributeTypeMap = [
    {
        "name": "statusDetail",
        "baseName": "statusDetail",
        "type": "StatusDetail"
    },
    {
        "name": "result",
        "baseName": "result",
        "type": "boolean"
    },
    {
        "name": "extra",
        "baseName": "extra",
        "type": "string"
    }
];
//# sourceMappingURL=showPromptResult.js.map