"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StatusDetail = void 0;
var StatusDetail;
(function (StatusDetail) {
    StatusDetail[StatusDetail["Success"] = 'Success'] = "Success";
    StatusDetail[StatusDetail["Timeout"] = 'Timeout'] = "Timeout";
    StatusDetail[StatusDetail["Cancelled"] = 'Cancelled'] = "Cancelled";
})(StatusDetail = exports.StatusDetail || (exports.StatusDetail = {}));
//# sourceMappingURL=statusDetail.js.map