/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TemplateButtonAction } from './templateButtonAction';

export class TemplateButton {
    'text'?: string | null;
    'action'?: TemplateButtonAction | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "TemplateButtonAction"
        }    ];

    static getAttributeTypeMap() {
        return TemplateButton.attributeTypeMap;
    }
}

