"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemplateTypeEnum = void 0;
var TemplateTypeEnum;
(function (TemplateTypeEnum) {
    TemplateTypeEnum[TemplateTypeEnum["T1"] = 'T1'] = "T1";
})(TemplateTypeEnum = exports.TemplateTypeEnum || (exports.TemplateTypeEnum = {}));
//# sourceMappingURL=templateTypeEnum.js.map