"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Template = void 0;
class Template {
    static getAttributeTypeMap() {
        return Template.attributeTypeMap;
    }
}
exports.Template = Template;
Template.discriminator = "templateType";
Template.attributeTypeMap = [
    {
        "name": "templateType",
        "baseName": "templateType",
        "type": "TemplateTypeEnum"
    }
];
//# sourceMappingURL=template.js.map