"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TicketAccess = void 0;
var TicketAccess;
(function (TicketAccess) {
    TicketAccess[TicketAccess["NUMBER_0"] = 0] = "NUMBER_0";
    TicketAccess[TicketAccess["NUMBER_1"] = 1] = "NUMBER_1";
    TicketAccess[TicketAccess["NUMBER_2"] = 2] = "NUMBER_2";
    TicketAccess[TicketAccess["NUMBER_3"] = 3] = "NUMBER_3";
})(TicketAccess = exports.TicketAccess || (exports.TicketAccess = {}));
//# sourceMappingURL=ticketAccess.js.map