/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateTicketDtoDetailTemplate } from './createTicketDtoDetailTemplate';
import { CreateTicketDtoTemplate } from './createTicketDtoTemplate';

export class UpdateTicketDto {
    'ticketId': string;
    'name': string;
    'data': string;
    'template': CreateTicketDtoTemplate;
    'detailTemplate': CreateTicketDtoDetailTemplate;
    'note': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ticketId",
            "baseName": "ticketId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "CreateTicketDtoTemplate"
        },
        {
            "name": "detailTemplate",
            "baseName": "detailTemplate",
            "type": "CreateTicketDtoDetailTemplate"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateTicketDto.attributeTypeMap;
    }
}

