"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VerifyDto = void 0;
class VerifyDto {
    static getAttributeTypeMap() {
        return VerifyDto.attributeTypeMap;
    }
}
exports.VerifyDto = VerifyDto;
VerifyDto.discriminator = undefined;
VerifyDto.attributeTypeMap = [
    {
        "name": "userName",
        "baseName": "userName",
        "type": "string"
    },
    {
        "name": "password",
        "baseName": "password",
        "type": "string"
    },
    {
        "name": "apiKey",
        "baseName": "apiKey",
        "type": "string"
    },
    {
        "name": "destApiKey",
        "baseName": "destApiKey",
        "type": "string"
    }
];
//# sourceMappingURL=verifyDto.js.map