"use strict";
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VerifyCredentialsUserIdResult = void 0;
class VerifyCredentialsUserIdResult {
    static getAttributeTypeMap() {
        return VerifyCredentialsUserIdResult.attributeTypeMap;
    }
}
exports.VerifyCredentialsUserIdResult = VerifyCredentialsUserIdResult;
VerifyCredentialsUserIdResult.discriminator = undefined;
VerifyCredentialsUserIdResult.attributeTypeMap = [
    {
        "name": "clientUri",
        "baseName": "clientUri",
        "type": "string"
    },
    {
        "name": "userName",
        "baseName": "userName",
        "type": "string"
    },
    {
        "name": "clientName",
        "baseName": "clientName",
        "type": "string"
    }
];
//# sourceMappingURL=verifyCredentialsUserIdResult.js.map