/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SendToTicketRequestActionsInner } from './sendToTicketRequestActionsInner';

export class SendToTicketRequest {
    'ticketId': string;
    'title': string;
    'body': string;
    'actions': Array<SendToTicketRequestActionsInner>;
    'image'?: string | null;
    'priority': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ticketId",
            "baseName": "ticketId",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<SendToTicketRequestActionsInner>"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SendToTicketRequest.attributeTypeMap;
    }
}

