/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReturnChoice } from './returnChoice';
import { StatusDetail } from './statusDetail';

export class ShowMultipleChoiceResponse {
    'statusDetail'?: StatusDetail;
    'choices': Array<ReturnChoice>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "statusDetail",
            "baseName": "statusDetail",
            "type": "StatusDetail"
        },
        {
            "name": "choices",
            "baseName": "choices",
            "type": "Array<ReturnChoice>"
        }    ];

    static getAttributeTypeMap() {
        return ShowMultipleChoiceResponse.attributeTypeMap;
    }
}

export namespace ShowMultipleChoiceResponse {
}
