/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ShowWebPageRequest {
    'communicationId': string;
    'loadingText': string;
    'url': string;
    'timeoutSek': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "communicationId",
            "baseName": "communicationId",
            "type": "string"
        },
        {
            "name": "loadingText",
            "baseName": "loadingText",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "timeoutSek",
            "baseName": "timeoutSek",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ShowWebPageRequest.attributeTypeMap;
    }
}

