/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DetailTemplate } from './detailTemplate';
import { DetailTemplateTypeEnum } from './detailTemplateTypeEnum';

export class WebPageDetailTemplate extends DetailTemplate {
    'loadingText'?: string | null;
    'url'?: string | null;
    'detailType': DetailTemplateTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "loadingText",
            "baseName": "loadingText",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "detailType",
            "baseName": "detailType",
            "type": "DetailTemplateTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WebPageDetailTemplate.attributeTypeMap);
    }
}

export namespace WebPageDetailTemplate {
}
