/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AuthenticationMethod = {
    Bio: 'Bio',
    Pin: 'Pin'
} as const;
export type AuthenticationMethod = typeof AuthenticationMethod[keyof typeof AuthenticationMethod];


export function AuthenticationMethodFromJSON(json: any): AuthenticationMethod {
    return AuthenticationMethodFromJSONTyped(json, false);
}

export function AuthenticationMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationMethod {
    return json as AuthenticationMethod;
}

export function AuthenticationMethodToJSON(value?: AuthenticationMethod | null): any {
    return value as any;
}

