/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BioAuthenticationRequest
 */
export interface BioAuthenticationRequest {
    /**
     * 
     * @type {string}
     * @memberof BioAuthenticationRequest
     */
    communicationId: string;
    /**
     * 
     * @type {string}
     * @memberof BioAuthenticationRequest
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof BioAuthenticationRequest
     */
    allowAlternative: boolean;
    /**
     * 
     * @type {string}
     * @memberof BioAuthenticationRequest
     */
    reason: string;
    /**
     * 
     * @type {number}
     * @memberof BioAuthenticationRequest
     */
    timeoutSek: number;
}

/**
 * Check if a given object implements the BioAuthenticationRequest interface.
 */
export function instanceOfBioAuthenticationRequest(value: object): boolean {
    if (!('communicationId' in value)) return false;
    if (!('title' in value)) return false;
    if (!('allowAlternative' in value)) return false;
    if (!('reason' in value)) return false;
    if (!('timeoutSek' in value)) return false;
    return true;
}

export function BioAuthenticationRequestFromJSON(json: any): BioAuthenticationRequest {
    return BioAuthenticationRequestFromJSONTyped(json, false);
}

export function BioAuthenticationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BioAuthenticationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'communicationId': json['communicationId'],
        'title': json['title'],
        'allowAlternative': json['allowAlternative'],
        'reason': json['reason'],
        'timeoutSek': json['timeoutSek'],
    };
}

export function BioAuthenticationRequestToJSON(value?: BioAuthenticationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'communicationId': value['communicationId'],
        'title': value['title'],
        'allowAlternative': value['allowAlternative'],
        'reason': value['reason'],
        'timeoutSek': value['timeoutSek'],
    };
}

