/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthenticationMethod } from './AuthenticationMethod';
import {
    AuthenticationMethodFromJSON,
    AuthenticationMethodFromJSONTyped,
    AuthenticationMethodToJSON,
} from './AuthenticationMethod';

/**
 * 
 * @export
 * @interface BioMetricAuthenticationResponse
 */
export interface BioMetricAuthenticationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BioMetricAuthenticationResponse
     */
    succeeded: boolean;
    /**
     * 
     * @type {AuthenticationMethod}
     * @memberof BioMetricAuthenticationResponse
     */
    authenticationMethod: AuthenticationMethod;
}

/**
 * Check if a given object implements the BioMetricAuthenticationResponse interface.
 */
export function instanceOfBioMetricAuthenticationResponse(value: object): boolean {
    if (!('succeeded' in value)) return false;
    if (!('authenticationMethod' in value)) return false;
    return true;
}

export function BioMetricAuthenticationResponseFromJSON(json: any): BioMetricAuthenticationResponse {
    return BioMetricAuthenticationResponseFromJSONTyped(json, false);
}

export function BioMetricAuthenticationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BioMetricAuthenticationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'succeeded': json['succeeded'],
        'authenticationMethod': AuthenticationMethodFromJSON(json['authenticationMethod']),
    };
}

export function BioMetricAuthenticationResponseToJSON(value?: BioMetricAuthenticationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'succeeded': value['succeeded'],
        'authenticationMethod': AuthenticationMethodToJSON(value['authenticationMethod']),
    };
}

