/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTicketResponse
 */
export interface CreateTicketResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateTicketResponse
     */
    ticketId: string;
}

/**
 * Check if a given object implements the CreateTicketResponse interface.
 */
export function instanceOfCreateTicketResponse(value: object): boolean {
    if (!('ticketId' in value)) return false;
    return true;
}

export function CreateTicketResponseFromJSON(json: any): CreateTicketResponse {
    return CreateTicketResponseFromJSONTyped(json, false);
}

export function CreateTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ticketId': json['ticketId'],
    };
}

export function CreateTicketResponseToJSON(value?: CreateTicketResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ticketId': value['ticketId'],
    };
}

