/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailTemplate1 } from './DetailTemplate1';
import {
    DetailTemplate1FromJSON,
    DetailTemplate1FromJSONTyped,
    DetailTemplate1ToJSON,
} from './DetailTemplate1';
import type { WebPageDetailTemplate } from './WebPageDetailTemplate';
import {
    WebPageDetailTemplateFromJSON,
    WebPageDetailTemplateFromJSONTyped,
    WebPageDetailTemplateToJSON,
} from './WebPageDetailTemplate';


/**
 * 
 * @export
 * @interface DetailTemplate
 */
export interface DetailTemplate {
    /**
     * 
     * @type {string}
     * @memberof DetailTemplate
     */
    readonly detailType: string;
}

/**
 * Check if a given object implements the DetailTemplate interface.
 */
export function instanceOfDetailTemplate(value: object): boolean {
    if (!('detailType' in value)) return false;
    return true;
}

export function DetailTemplateFromJSON(json: any): DetailTemplate {
    return DetailTemplateFromJSONTyped(json, false);
}

export function DetailTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailTemplate {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['detailType'] === 'DT1') {
            return DetailTemplate1FromJSONTyped(json, true);
        }
        if (json['detailType'] === 'WebPageDetailTemplate') {
            return WebPageDetailTemplateFromJSONTyped(json, true);
        }
    }
    return {
        
        'detailType': json['detailType'],
    };
}

export function DetailTemplateToJSON(value?: DetailTemplate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

