/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusDetail } from './StatusDetail';
import {
    StatusDetailFromJSON,
    StatusDetailFromJSONTyped,
    StatusDetailToJSON,
} from './StatusDetail';

/**
 * 
 * @export
 * @interface DeviceException
 */
export interface DeviceException {
    /**
     * 
     * @type {StatusDetail}
     * @memberof DeviceException
     */
    statusDetail: StatusDetail;
}

/**
 * Check if a given object implements the DeviceException interface.
 */
export function instanceOfDeviceException(value: object): boolean {
    if (!('statusDetail' in value)) return false;
    return true;
}

export function DeviceExceptionFromJSON(json: any): DeviceException {
    return DeviceExceptionFromJSONTyped(json, false);
}

export function DeviceExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceException {
    if (json == null) {
        return json;
    }
    return {
        
        'statusDetail': StatusDetailFromJSON(json['statusDetail']),
    };
}

export function DeviceExceptionToJSON(value?: DeviceException | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusDetail': StatusDetailToJSON(value['statusDetail']),
    };
}

