/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseAction } from './BaseAction';
import {
    BaseActionFromJSON,
    BaseActionFromJSONTyped,
    BaseActionToJSON,
} from './BaseAction';

import {
} from './index';

/**
 * 
 * @export
 * @interface RefreshTicketListAction
 */
export interface RefreshTicketListAction extends BaseAction {
    /**
     * 
     * @type {string}
     * @memberof RefreshTicketListAction
     */
    readonly actionType: string;
}

/**
 * Check if a given object implements the RefreshTicketListAction interface.
 */
export function instanceOfRefreshTicketListAction(value: object): boolean {
    if (!('actionType' in value)) return false;
    return true;
}

export function RefreshTicketListActionFromJSON(json: any): RefreshTicketListAction {
    return RefreshTicketListActionFromJSONTyped(json, false);
}

export function RefreshTicketListActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTicketListAction {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...BaseActionFromJSONTyped(json, ignoreDiscriminator),
        'actionType': json['actionType'],
    };
}

export function RefreshTicketListActionToJSON(value?: RefreshTicketListAction | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseActionToJSON(value),
    };
}

