/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseAction } from './BaseAction';
import {
    BaseActionFromJSON,
    BaseActionFromJSONTyped,
    BaseActionToJSON,
} from './BaseAction';

import {
} from './index';

/**
 * 
 * @export
 * @interface RefreshTicketAction
 */
export interface RefreshTicketAction extends BaseAction {
    /**
     * 
     * @type {string}
     * @memberof RefreshTicketAction
     */
    ticketId: string;
    /**
     * 
     * @type {string}
     * @memberof RefreshTicketAction
     */
    readonly actionType: string;
}

/**
 * Check if a given object implements the RefreshTicketAction interface.
 */
export function instanceOfRefreshTicketAction(value: object): boolean {
    if (!('ticketId' in value)) return false;
    if (!('actionType' in value)) return false;
    return true;
}

export function RefreshTicketActionFromJSON(json: any): RefreshTicketAction {
    return RefreshTicketActionFromJSONTyped(json, false);
}

export function RefreshTicketActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTicketAction {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...BaseActionFromJSONTyped(json, ignoreDiscriminator),
        'ticketId': json['ticketId'],
        'actionType': json['actionType'],
    };
}

export function RefreshTicketActionToJSON(value?: RefreshTicketAction | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseActionToJSON(value),
        'ticketId': value['ticketId'],
    };
}

