/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReturnChoice
 */
export interface ReturnChoice {
    /**
     * 
     * @type {number}
     * @memberof ReturnChoice
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReturnChoice
     */
    value: boolean;
}

/**
 * Check if a given object implements the ReturnChoice interface.
 */
export function instanceOfReturnChoice(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function ReturnChoiceFromJSON(json: any): ReturnChoice {
    return ReturnChoiceFromJSONTyped(json, false);
}

export function ReturnChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnChoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
    };
}

export function ReturnChoiceToJSON(value?: ReturnChoice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'value': value['value'],
    };
}

