/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendToTicketRequestActionsInner } from './SendToTicketRequestActionsInner';
import {
    SendToTicketRequestActionsInnerFromJSON,
    SendToTicketRequestActionsInnerFromJSONTyped,
    SendToTicketRequestActionsInnerToJSON,
} from './SendToTicketRequestActionsInner';

/**
 * 
 * @export
 * @interface SendToTicketRequest
 */
export interface SendToTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof SendToTicketRequest
     */
    ticketId: string;
    /**
     * 
     * @type {string}
     * @memberof SendToTicketRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SendToTicketRequest
     */
    body: string;
    /**
     * 
     * @type {Array<SendToTicketRequestActionsInner>}
     * @memberof SendToTicketRequest
     */
    actions: Array<SendToTicketRequestActionsInner>;
    /**
     * 
     * @type {string}
     * @memberof SendToTicketRequest
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof SendToTicketRequest
     */
    priority: number;
}

/**
 * Check if a given object implements the SendToTicketRequest interface.
 */
export function instanceOfSendToTicketRequest(value: object): boolean {
    if (!('ticketId' in value)) return false;
    if (!('title' in value)) return false;
    if (!('body' in value)) return false;
    if (!('actions' in value)) return false;
    if (!('priority' in value)) return false;
    return true;
}

export function SendToTicketRequestFromJSON(json: any): SendToTicketRequest {
    return SendToTicketRequestFromJSONTyped(json, false);
}

export function SendToTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendToTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ticketId': json['ticketId'],
        'title': json['title'],
        'body': json['body'],
        'actions': ((json['actions'] as Array<any>).map(SendToTicketRequestActionsInnerFromJSON)),
        'image': json['image'] == null ? undefined : json['image'],
        'priority': json['priority'],
    };
}

export function SendToTicketRequestToJSON(value?: SendToTicketRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ticketId': value['ticketId'],
        'title': value['title'],
        'body': value['body'],
        'actions': ((value['actions'] as Array<any>).map(SendToTicketRequestActionsInnerToJSON)),
        'image': value['image'],
        'priority': value['priority'],
    };
}

