/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseAction } from './BaseAction';
import {
    BaseActionFromJSON,
    BaseActionFromJSONTyped,
    BaseActionToJSON,
} from './BaseAction';

import {
} from './index';

/**
 * 
 * @export
 * @interface SensorAction
 */
export interface SensorAction extends BaseAction {
    /**
     * 
     * @type {string}
     * @memberof SensorAction
     */
    sensorId: string;
    /**
     * 
     * @type {string}
     * @memberof SensorAction
     */
    readonly actionType: string;
}

/**
 * Check if a given object implements the SensorAction interface.
 */
export function instanceOfSensorAction(value: object): boolean {
    if (!('sensorId' in value)) return false;
    if (!('actionType' in value)) return false;
    return true;
}

export function SensorActionFromJSON(json: any): SensorAction {
    return SensorActionFromJSONTyped(json, false);
}

export function SensorActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorAction {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...BaseActionFromJSONTyped(json, ignoreDiscriminator),
        'sensorId': json['sensorId'],
        'actionType': json['actionType'],
    };
}

export function SensorActionToJSON(value?: SensorAction | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseActionToJSON(value),
        'sensorId': value['sensorId'],
    };
}

