/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SensorType = {
    Normal: 'Normal',
    Push: 'Push',
    Beacon: 'Beacon'
} as const;
export type SensorType = typeof SensorType[keyof typeof SensorType];


export function SensorTypeFromJSON(json: any): SensorType {
    return SensorTypeFromJSONTyped(json, false);
}

export function SensorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorType {
    return json as SensorType;
}

export function SensorTypeToJSON(value?: SensorType | null): any {
    return value as any;
}

