/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sensor } from './Sensor';
import {
    SensorFromJSON,
    SensorFromJSONTyped,
    SensorToJSON,
} from './Sensor';

/**
 * 
 * @export
 * @interface SensorsConfigurationResponse
 */
export interface SensorsConfigurationResponse {
    /**
     * 
     * @type {Array<Sensor>}
     * @memberof SensorsConfigurationResponse
     */
    sensors: Array<Sensor>;
}

/**
 * Check if a given object implements the SensorsConfigurationResponse interface.
 */
export function instanceOfSensorsConfigurationResponse(value: object): boolean {
    if (!('sensors' in value)) return false;
    return true;
}

export function SensorsConfigurationResponseFromJSON(json: any): SensorsConfigurationResponse {
    return SensorsConfigurationResponseFromJSONTyped(json, false);
}

export function SensorsConfigurationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorsConfigurationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sensors': ((json['sensors'] as Array<any>).map(SensorFromJSON)),
    };
}

export function SensorsConfigurationResponseToJSON(value?: SensorsConfigurationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sensors': ((value['sensors'] as Array<any>).map(SensorToJSON)),
    };
}

