/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShowWebPageRequest
 */
export interface ShowWebPageRequest {
    /**
     * 
     * @type {string}
     * @memberof ShowWebPageRequest
     */
    communicationId: string;
    /**
     * 
     * @type {string}
     * @memberof ShowWebPageRequest
     */
    loadingText: string;
    /**
     * 
     * @type {string}
     * @memberof ShowWebPageRequest
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof ShowWebPageRequest
     */
    timeoutSek: number;
}

/**
 * Check if a given object implements the ShowWebPageRequest interface.
 */
export function instanceOfShowWebPageRequest(value: object): boolean {
    if (!('communicationId' in value)) return false;
    if (!('loadingText' in value)) return false;
    if (!('url' in value)) return false;
    if (!('timeoutSek' in value)) return false;
    return true;
}

export function ShowWebPageRequestFromJSON(json: any): ShowWebPageRequest {
    return ShowWebPageRequestFromJSONTyped(json, false);
}

export function ShowWebPageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowWebPageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'communicationId': json['communicationId'],
        'loadingText': json['loadingText'],
        'url': json['url'],
        'timeoutSek': json['timeoutSek'],
    };
}

export function ShowWebPageRequestToJSON(value?: ShowWebPageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'communicationId': value['communicationId'],
        'loadingText': value['loadingText'],
        'url': value['url'],
        'timeoutSek': value['timeoutSek'],
    };
}

