/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReturnChoice } from './ReturnChoice';
import {
    ReturnChoiceFromJSON,
    ReturnChoiceFromJSONTyped,
    ReturnChoiceToJSON,
} from './ReturnChoice';
import type { StatusDetail } from './StatusDetail';
import {
    StatusDetailFromJSON,
    StatusDetailFromJSONTyped,
    StatusDetailToJSON,
} from './StatusDetail';

/**
 * 
 * @export
 * @interface ShowMultipleChoiceResponse
 */
export interface ShowMultipleChoiceResponse {
    /**
     * 
     * @type {StatusDetail}
     * @memberof ShowMultipleChoiceResponse
     */
    statusDetail?: StatusDetail;
    /**
     * 
     * @type {Array<ReturnChoice>}
     * @memberof ShowMultipleChoiceResponse
     */
    choices: Array<ReturnChoice>;
}

/**
 * Check if a given object implements the ShowMultipleChoiceResponse interface.
 */
export function instanceOfShowMultipleChoiceResponse(value: object): boolean {
    if (!('choices' in value)) return false;
    return true;
}

export function ShowMultipleChoiceResponseFromJSON(json: any): ShowMultipleChoiceResponse {
    return ShowMultipleChoiceResponseFromJSONTyped(json, false);
}

export function ShowMultipleChoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowMultipleChoiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusDetail': json['statusDetail'] == null ? undefined : StatusDetailFromJSON(json['statusDetail']),
        'choices': ((json['choices'] as Array<any>).map(ReturnChoiceFromJSON)),
    };
}

export function ShowMultipleChoiceResponseToJSON(value?: ShowMultipleChoiceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusDetail': StatusDetailToJSON(value['statusDetail']),
        'choices': ((value['choices'] as Array<any>).map(ReturnChoiceToJSON)),
    };
}

