/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseAction } from './BaseAction';
import {
    BaseActionFromJSON,
    BaseActionFromJSONTyped,
    BaseActionToJSON,
} from './BaseAction';

import {
} from './index';

/**
 * 
 * @export
 * @interface ShowUrlAction
 */
export interface ShowUrlAction extends BaseAction {
    /**
     * 
     * @type {string}
     * @memberof ShowUrlAction
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ShowUrlAction
     */
    readonly actionType: string;
}

/**
 * Check if a given object implements the ShowUrlAction interface.
 */
export function instanceOfShowUrlAction(value: object): boolean {
    if (!('url' in value)) return false;
    if (!('actionType' in value)) return false;
    return true;
}

export function ShowUrlActionFromJSON(json: any): ShowUrlAction {
    return ShowUrlActionFromJSONTyped(json, false);
}

export function ShowUrlActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowUrlAction {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...BaseActionFromJSONTyped(json, ignoreDiscriminator),
        'url': json['url'],
        'actionType': json['actionType'],
    };
}

export function ShowUrlActionToJSON(value?: ShowUrlAction | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseActionToJSON(value),
        'url': value['url'],
    };
}

