/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShowQrCodeRequest
 */
export interface ShowQrCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof ShowQrCodeRequest
     */
    communicationId: string;
    /**
     * 
     * @type {string}
     * @memberof ShowQrCodeRequest
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ShowQrCodeRequest
     */
    qrCode: string;
    /**
     * 
     * @type {number}
     * @memberof ShowQrCodeRequest
     */
    timeoutSek: number;
    /**
     * 
     * @type {string}
     * @memberof ShowQrCodeRequest
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ShowQrCodeRequest
     */
    title: string;
}

/**
 * Check if a given object implements the ShowQrCodeRequest interface.
 */
export function instanceOfShowQrCodeRequest(value: object): boolean {
    if (!('communicationId' in value)) return false;
    if (!('message' in value)) return false;
    if (!('qrCode' in value)) return false;
    if (!('timeoutSek' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function ShowQrCodeRequestFromJSON(json: any): ShowQrCodeRequest {
    return ShowQrCodeRequestFromJSONTyped(json, false);
}

export function ShowQrCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowQrCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'communicationId': json['communicationId'],
        'message': json['message'],
        'qrCode': json['qrCode'],
        'timeoutSek': json['timeoutSek'],
        'image': json['image'] == null ? undefined : json['image'],
        'title': json['title'],
    };
}

export function ShowQrCodeRequestToJSON(value?: ShowQrCodeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'communicationId': value['communicationId'],
        'message': value['message'],
        'qrCode': value['qrCode'],
        'timeoutSek': value['timeoutSek'],
        'image': value['image'],
        'title': value['title'],
    };
}

