/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShowMenuRequest
 */
export interface ShowMenuRequest {
    /**
     * 
     * @type {string}
     * @memberof ShowMenuRequest
     */
    communicationId: string;
    /**
     * 
     * @type {string}
     * @memberof ShowMenuRequest
     */
    message: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ShowMenuRequest
     */
    options: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ShowMenuRequest
     */
    timeoutSek: number;
    /**
     * 
     * @type {string}
     * @memberof ShowMenuRequest
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ShowMenuRequest
     */
    title: string;
}

/**
 * Check if a given object implements the ShowMenuRequest interface.
 */
export function instanceOfShowMenuRequest(value: object): boolean {
    if (!('communicationId' in value)) return false;
    if (!('message' in value)) return false;
    if (!('options' in value)) return false;
    if (!('timeoutSek' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function ShowMenuRequestFromJSON(json: any): ShowMenuRequest {
    return ShowMenuRequestFromJSONTyped(json, false);
}

export function ShowMenuRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowMenuRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'communicationId': json['communicationId'],
        'message': json['message'],
        'options': json['options'],
        'timeoutSek': json['timeoutSek'],
        'image': json['image'] == null ? undefined : json['image'],
        'title': json['title'],
    };
}

export function ShowMenuRequestToJSON(value?: ShowMenuRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'communicationId': value['communicationId'],
        'message': value['message'],
        'options': value['options'],
        'timeoutSek': value['timeoutSek'],
        'image': value['image'],
        'title': value['title'],
    };
}

