/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShowPromptRequest
 */
export interface ShowPromptRequest {
    /**
     * 
     * @type {string}
     * @memberof ShowPromptRequest
     */
    communicationId: string;
    /**
     * 
     * @type {string}
     * @memberof ShowPromptRequest
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ShowPromptRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ShowPromptRequest
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ShowPromptRequest
     */
    yes: string;
    /**
     * 
     * @type {string}
     * @memberof ShowPromptRequest
     */
    no: string;
    /**
     * 
     * @type {number}
     * @memberof ShowPromptRequest
     */
    timeoutSek: number;
}

/**
 * Check if a given object implements the ShowPromptRequest interface.
 */
export function instanceOfShowPromptRequest(value: object): boolean {
    if (!('communicationId' in value)) return false;
    if (!('title' in value)) return false;
    if (!('message' in value)) return false;
    if (!('yes' in value)) return false;
    if (!('no' in value)) return false;
    if (!('timeoutSek' in value)) return false;
    return true;
}

export function ShowPromptRequestFromJSON(json: any): ShowPromptRequest {
    return ShowPromptRequestFromJSONTyped(json, false);
}

export function ShowPromptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowPromptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'communicationId': json['communicationId'],
        'image': json['image'] == null ? undefined : json['image'],
        'title': json['title'],
        'message': json['message'],
        'yes': json['yes'],
        'no': json['no'],
        'timeoutSek': json['timeoutSek'],
    };
}

export function ShowPromptRequestToJSON(value?: ShowPromptRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'communicationId': value['communicationId'],
        'image': value['image'],
        'title': value['title'],
        'message': value['message'],
        'yes': value['yes'],
        'no': value['no'],
        'timeoutSek': value['timeoutSek'],
    };
}

