/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusDetail } from './StatusDetail';
import {
    StatusDetailFromJSON,
    StatusDetailFromJSONTyped,
    StatusDetailToJSON,
} from './StatusDetail';

/**
 * 
 * @export
 * @interface ShowMenuResponse
 */
export interface ShowMenuResponse {
    /**
     * 
     * @type {StatusDetail}
     * @memberof ShowMenuResponse
     */
    statusDetail?: StatusDetail;
    /**
     * 
     * @type {string}
     * @memberof ShowMenuResponse
     */
    selectedValue: string;
}

/**
 * Check if a given object implements the ShowMenuResponse interface.
 */
export function instanceOfShowMenuResponse(value: object): boolean {
    if (!('selectedValue' in value)) return false;
    return true;
}

export function ShowMenuResponseFromJSON(json: any): ShowMenuResponse {
    return ShowMenuResponseFromJSONTyped(json, false);
}

export function ShowMenuResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowMenuResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusDetail': json['statusDetail'] == null ? undefined : StatusDetailFromJSON(json['statusDetail']),
        'selectedValue': json['selectedValue'],
    };
}

export function ShowMenuResponseToJSON(value?: ShowMenuResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusDetail': StatusDetailToJSON(value['statusDetail']),
        'selectedValue': value['selectedValue'],
    };
}

