/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Choice } from './Choice';
import {
    ChoiceFromJSON,
    ChoiceFromJSONTyped,
    ChoiceToJSON,
} from './Choice';

/**
 * 
 * @export
 * @interface ShowMultipleChoiceRequest
 */
export interface ShowMultipleChoiceRequest {
    /**
     * 
     * @type {string}
     * @memberof ShowMultipleChoiceRequest
     */
    communicationId: string;
    /**
     * 
     * @type {string}
     * @memberof ShowMultipleChoiceRequest
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ShowMultipleChoiceRequest
     */
    closeText: string;
    /**
     * 
     * @type {Array<Choice>}
     * @memberof ShowMultipleChoiceRequest
     */
    options: Array<Choice>;
    /**
     * 
     * @type {number}
     * @memberof ShowMultipleChoiceRequest
     */
    timeoutSek: number;
    /**
     * 
     * @type {string}
     * @memberof ShowMultipleChoiceRequest
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ShowMultipleChoiceRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the ShowMultipleChoiceRequest interface.
 */
export function instanceOfShowMultipleChoiceRequest(value: object): boolean {
    if (!('communicationId' in value)) return false;
    if (!('message' in value)) return false;
    if (!('closeText' in value)) return false;
    if (!('options' in value)) return false;
    if (!('timeoutSek' in value)) return false;
    return true;
}

export function ShowMultipleChoiceRequestFromJSON(json: any): ShowMultipleChoiceRequest {
    return ShowMultipleChoiceRequestFromJSONTyped(json, false);
}

export function ShowMultipleChoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowMultipleChoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'communicationId': json['communicationId'],
        'message': json['message'],
        'closeText': json['closeText'],
        'options': ((json['options'] as Array<any>).map(ChoiceFromJSON)),
        'timeoutSek': json['timeoutSek'],
        'image': json['image'] == null ? undefined : json['image'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ShowMultipleChoiceRequestToJSON(value?: ShowMultipleChoiceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'communicationId': value['communicationId'],
        'message': value['message'],
        'closeText': value['closeText'],
        'options': ((value['options'] as Array<any>).map(ChoiceToJSON)),
        'timeoutSek': value['timeoutSek'],
        'image': value['image'],
        'title': value['title'],
    };
}

