/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusDetail } from './StatusDetail';
import {
    StatusDetailFromJSON,
    StatusDetailFromJSONTyped,
    StatusDetailToJSON,
} from './StatusDetail';

/**
 * 
 * @export
 * @interface ShowWebPageResponse
 */
export interface ShowWebPageResponse {
    /**
     * 
     * @type {StatusDetail}
     * @memberof ShowWebPageResponse
     */
    statusDetail?: StatusDetail;
    /**
     * 
     * @type {string}
     * @memberof ShowWebPageResponse
     */
    result: string;
}

/**
 * Check if a given object implements the ShowWebPageResponse interface.
 */
export function instanceOfShowWebPageResponse(value: object): boolean {
    if (!('result' in value)) return false;
    return true;
}

export function ShowWebPageResponseFromJSON(json: any): ShowWebPageResponse {
    return ShowWebPageResponseFromJSONTyped(json, false);
}

export function ShowWebPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowWebPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusDetail': json['statusDetail'] == null ? undefined : StatusDetailFromJSON(json['statusDetail']),
        'result': json['result'],
    };
}

export function ShowWebPageResponseToJSON(value?: ShowWebPageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusDetail': StatusDetailToJSON(value['statusDetail']),
        'result': value['result'],
    };
}

