/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketActive
 */
export interface TicketActive {
    /**
     * 
     * @type {string}
     * @memberof TicketActive
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketActive
     */
    ticketName?: string;
}

/**
 * Check if a given object implements the TicketActive interface.
 */
export function instanceOfTicketActive(value: object): boolean {
    return true;
}

export function TicketActiveFromJSON(json: any): TicketActive {
    return TicketActiveFromJSONTyped(json, false);
}

export function TicketActiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketActive {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ticketName': json['ticketName'] == null ? undefined : json['ticketName'],
    };
}

export function TicketActiveToJSON(value?: TicketActive | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'ticketName': value['ticketName'],
    };
}

