/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateTicketRequestDetailTemplate } from './CreateTicketRequestDetailTemplate';
import {
    CreateTicketRequestDetailTemplateFromJSON,
    CreateTicketRequestDetailTemplateFromJSONTyped,
    CreateTicketRequestDetailTemplateToJSON,
} from './CreateTicketRequestDetailTemplate';
import type { CreateTicketRequestTemplate } from './CreateTicketRequestTemplate';
import {
    CreateTicketRequestTemplateFromJSON,
    CreateTicketRequestTemplateFromJSONTyped,
    CreateTicketRequestTemplateToJSON,
} from './CreateTicketRequestTemplate';

/**
 * 
 * @export
 * @interface UpdateTicketRequest
 */
export interface UpdateTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    ticketId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    data: string;
    /**
     * 
     * @type {CreateTicketRequestTemplate}
     * @memberof UpdateTicketRequest
     */
    template: CreateTicketRequestTemplate;
    /**
     * 
     * @type {CreateTicketRequestDetailTemplate}
     * @memberof UpdateTicketRequest
     */
    detailTemplate: CreateTicketRequestDetailTemplate;
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    note: string;
}

/**
 * Check if a given object implements the UpdateTicketRequest interface.
 */
export function instanceOfUpdateTicketRequest(value: object): boolean {
    if (!('ticketId' in value)) return false;
    if (!('name' in value)) return false;
    if (!('data' in value)) return false;
    if (!('template' in value)) return false;
    if (!('detailTemplate' in value)) return false;
    if (!('note' in value)) return false;
    return true;
}

export function UpdateTicketRequestFromJSON(json: any): UpdateTicketRequest {
    return UpdateTicketRequestFromJSONTyped(json, false);
}

export function UpdateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ticketId': json['ticketId'],
        'name': json['name'],
        'data': json['data'],
        'template': CreateTicketRequestTemplateFromJSON(json['template']),
        'detailTemplate': CreateTicketRequestDetailTemplateFromJSON(json['detailTemplate']),
        'note': json['note'],
    };
}

export function UpdateTicketRequestToJSON(value?: UpdateTicketRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ticketId': value['ticketId'],
        'name': value['name'],
        'data': value['data'],
        'template': CreateTicketRequestTemplateToJSON(value['template']),
        'detailTemplate': CreateTicketRequestDetailTemplateToJSON(value['detailTemplate']),
        'note': value['note'],
    };
}

