/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyCredentialsResult
 */
export interface VerifyCredentialsResult {
    /**
     * 
     * @type {string}
     * @memberof VerifyCredentialsResult
     */
    clientUri: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCredentialsResult
     */
    clientName: string;
}

/**
 * Check if a given object implements the VerifyCredentialsResult interface.
 */
export function instanceOfVerifyCredentialsResult(value: object): boolean {
    if (!('clientUri' in value)) return false;
    if (!('clientName' in value)) return false;
    return true;
}

export function VerifyCredentialsResultFromJSON(json: any): VerifyCredentialsResult {
    return VerifyCredentialsResultFromJSONTyped(json, false);
}

export function VerifyCredentialsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyCredentialsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'clientUri': json['clientUri'],
        'clientName': json['clientName'],
    };
}

export function VerifyCredentialsResultToJSON(value?: VerifyCredentialsResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'clientUri': value['clientUri'],
        'clientName': value['clientName'],
    };
}

