/* tslint:disable */
/* eslint-disable */
/**
 * Isveski Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailTemplate } from './DetailTemplate';
import {
    DetailTemplateFromJSON,
    DetailTemplateFromJSONTyped,
    DetailTemplateToJSON,
} from './DetailTemplate';

import {
} from './index';

/**
 * 
 * @export
 * @interface WebPageDetailTemplate
 */
export interface WebPageDetailTemplate extends DetailTemplate {
    /**
     * 
     * @type {string}
     * @memberof WebPageDetailTemplate
     */
    loadingText?: string;
    /**
     * 
     * @type {string}
     * @memberof WebPageDetailTemplate
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WebPageDetailTemplate
     */
    readonly detailType: string;
}

/**
 * Check if a given object implements the WebPageDetailTemplate interface.
 */
export function instanceOfWebPageDetailTemplate(value: object): boolean {
    if (!('detailType' in value)) return false;
    return true;
}

export function WebPageDetailTemplateFromJSON(json: any): WebPageDetailTemplate {
    return WebPageDetailTemplateFromJSONTyped(json, false);
}

export function WebPageDetailTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebPageDetailTemplate {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...DetailTemplateFromJSONTyped(json, ignoreDiscriminator),
        'loadingText': json['loadingText'] == null ? undefined : json['loadingText'],
        'url': json['url'] == null ? undefined : json['url'],
        'detailType': json['detailType'],
    };
}

export function WebPageDetailTemplateToJSON(value?: WebPageDetailTemplate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...DetailTemplateToJSON(value),
        'loadingText': value['loadingText'],
        'url': value['url'],
    };
}

